### PR TITLE
Redis.lock must set lock before returning it

### PR DESCRIPTION
**Pull request by tmornini**

### CODE REVIEW

**Comment by mlanett** [comment]
Oops indeed.

**Comment by tmornini** [comment]
:-)

**Comment by tmornini** [comment]
@mlanett Any plans for a new release? :-)

**Comment by mlanett** [comment]
Oh yeah, I was about to, but all the tests failed. Turns out that the various test frameworks have been updated over time, whereas our lock files are in the past. So I wanted to update the tests for newish frameworks (now partly done) and then release.

**Comment by tmornini** [comment]
Weird. The tests passed just 9 days before!

Did you use the committed Gemfile and Gemfile.lock?

I did! :-)

**Pull request merged**
